# Generated by Django 4.0.3 on 2022-03-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs_lib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
