# Generated by Django 4.0.3 on 2022-03-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs_lib', '0002_songs_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='genre',
            field=models.CharField(default='music', max_length=225),
            preserve_default=False,
        ),
    ]
